### PR TITLE
fix issue 184 by marking the destination as a packed struct

### LINKED ISSUE #184: u64 -> [u8; 8] transmute triggers spurious alignment error
```rust
// test.rs

pub fn main() {
    let bytes: [u8; 8] = unsafe { ::std::mem::transmute(0u64) };
    let _: &[u8] = &bytes;
}
```

```
$ cargo run --bin miri -- test.rs
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/miri test.rs`
error: tried to access memory with alignment 1, but alignment 8 is required
 --> test.rs:5:20
  |
5 |     let _: &[u8] = &bytes;
  |                    ^^^^^^
  |
note: inside call to main
 --> test.rs:3:1
  |
3 | / pub fn main() {
4 | |     let bytes: [u8; 8] = unsafe { ::std::mem::transmute(0u64) };
5 | |     let _: &[u8] = &bytes;
6 | | }
  | |_^

error: aborting due to previous error(s)
```

### PR DESCRIPTION
**Pull request by dwrensha**
Fixes #184.

### CODE REVIEW

File: src/terminator/intrinsic.rs [hunk 1]
```diff
@@ -383,8 +383,17 @@ impl<'a, 'tcx> EvalContext<'a, 'tcx> {
             }
 
             "transmute" => {
+                let src_ty = substs.type_at(0);
                 let dest_ty = substs.type_at(1);
-                self.write_value(arg_vals[0], dest, dest_ty)?;
+                let (_, src_align) = self.size_and_align_of_dst(src_ty, arg_vals[0])?;
+                let (size, dest_align) = self.size_and_align_of_dst(dest_ty, arg_vals[0])?;
```
Comment (oli-obk) [inline src/terminator/intrinsic.rs]: Transmute doesn't take DSTs. Calling the type_align and type_size methods is better imo.

Comment (dwrensha) [inline src/terminator/intrinsic.rs]: Good point. For some reason I was mentally expanding the "dst" part of `size_and_align_of_dst()` into "destination", not "dynamically sized type".

**Comment by oli-obk** [comment]
Thanks
