### PR TITLE
Make Reallocate & Deallocate less permissive

### LINKED ISSUE #214: Reallocate/Deallocate is too permissive
The following test should fail at the deref, because reallocate could change the address:
```rust
#[feature(heap_api)]

mod std::heal::{allocate, reallocate};
fn main() {
    let x = allocate(1, 1);
    let y = reallocate(1, 1, 1);
    let _ = *x;
}
```

Also, reallocate currently does not validate the `old_size`. This should fail:
```rust
#[feature(heap_api)]

mod std::heal::{allocate, reallocate};
fn main() {
    let x = allocate(1, 1);
    let y = reallocate(2, 1, 1);
}
```
Nor does it validate the alignment. This should fail:
```rust
#[feature(heap_api)]

mod std::heal::{allocate, reallocate};
fn main() {
    let x = allocate(1, 2);
    let y = reallocate(1, 2, 1) as *const u16;
    let _ = *y;
}
```

I was going to do this, but it'll probably conflict with <https://github.com/solson/miri/issues/204#issuecomment-310762968>.

### PR DESCRIPTION
**Pull request by RalfJung**
Fixes #214

### CODE REVIEW

**Comment by RalfJung** [comment]
Most of the new tests use "error-pattern" rather than an embedded "//~ ERROR". I'd like to use the latter, but it doesn't work -- compiletest-rs does not seem to recognize the error message that miri prints, to it can't match the pattern.

File: src/memory.rs [hunk 1]
```diff
@@ -223,58 +223,74 @@ impl<'a, 'tcx> Memory<'a, 'tcx> {
...
+            return Err(EvalError::DeallocateNonBasePtr);
         }
 
-        if let Some(alloc) = self.alloc_map.remove(&ptr.alloc_id) {
-            self.memory_usage -= alloc.bytes.len() as u64;
-        } else {
-            debug!("deallocated a pointer twice: {}", ptr.alloc_id);
-            // TODO(solson): Report error about erroneous free. This is blocked on properly tracking
-            // already-dropped state since this if-statement is entered even in safe code without
-            // it.
```
Comment (RalfJung) [inline src/memory.rs]: Btw, I have no idea what this comment refers to. Certainly all the code executed by the test suite does not actually end up in this block -- and it should not. Maybe enough things changed in miri's architecture that make this comment no longer apply.

**Comment by oli-obk** [comment]
> Most of the new tests use "error-pattern" rather than an embedded "//~ ERROR". I'd like to use the latter, but it doesn't work -- compiletest-rs does not seem to recognize the error message that miri prints, to it can't match the pattern.

We could just move to UI tests, then we get the entire backtrace. Errors due to recursion limits and such should stay compile-fail tests though.

The issue with `//~ ERROR` is that that one specific line does not have an error, but the error is occurring down the callstack

File: src/memory.rs [hunk 2]
```diff
@@ -223,58 +223,74 @@ impl<'a, 'tcx> Memory<'a, 'tcx> {
...
             let alloc = self.get_mut(ptr.alloc_id)?;
-            // FIXME: check alignment here
             // `as usize` is fine here, since it is smaller than `size`, which came from a usize
             alloc.bytes.truncate(new_size as usize);
             alloc.bytes.shrink_to_fit();
             alloc.undef_mask.truncate(new_size);
         }
 
-        Ok(Pointer::new(ptr.alloc_id, 0))
+        // Change allocation ID.  We do this after the above to be able to re-use methods like `clear_relocations`.
```
Comment (oli-obk) [inline src/memory.rs]: I wonder if we should just drop the `size > new_size` branch and unconditionally run the first branch. It's not like someone's going to be evaluating `reallocate` in a tight loop.

Comment (oli-obk) [inline src/memory.rs]: oh nevermind, I thought we allocated, copied and deallocated there...

File: src/memory.rs (hunk 1 above)
Comment (oli-obk) [inline src/memory.rs]: Yea, this used to happen, not sure whether MIR changes or miri changes fixed it, but I've not seen that message in traces in a long time.

File: src/memory.rs [hunk 3]
```diff
@@ -223,58 +223,74 @@ impl<'a, 'tcx> Memory<'a, 'tcx> {
...
-        if let Some(alloc) = self.alloc_map.remove(&ptr.alloc_id) {
-            self.memory_usage -= alloc.bytes.len() as u64;
-        } else {
-            debug!("deallocated a pointer twice: {}", ptr.alloc_id);
-            // TODO(solson): Report error about erroneous free. This is blocked on properly tracking
-            // already-dropped state since this if-statement is entered even in safe code without
-            // it.
+        {
+            // Some code somewhere seems to rely on us *not* removing the allocation when we yield this kind of error.
+            // So we do this test in advance.
```
Comment (oli-obk) [inline src/memory.rs]: The deallocation of locals has this check: https://github.com/solson/miri/blob/10ec543b9e056269d4b439dc8a6f48f11151c936/src/eval_context.rs#L416 

This happens when we deallocate the locals required to compute a static, but don't want to deallocate those locals that the static has a reference to.

File: src/memory.rs [hunk 4]
```diff
@@ -223,58 +223,74 @@ impl<'a, 'tcx> Memory<'a, 'tcx> {
...
+            id
+        };
+
+        Ok(Pointer::new(id, 0))
     }
 
     // TODO(solson): See comment on `reallocate`.
-    pub fn deallocate(&mut self, ptr: Pointer) -> EvalResult<'tcx> {
-        if ptr.offset != 0 {
+    pub fn deallocate(&mut self, ptr: Pointer, size_and_align: Option<(u64, u64)>) -> EvalResult<'tcx> {
```
Comment (oli-obk) [inline src/memory.rs]: I don't think these should be optional. Instead things like `free` should pass the same args as `malloc` passes to `allocate`.

File: src/memory.rs (hunk 2 above)
Comment (RalfJung) [inline src/memory.rs]: Yeah I wondered if maybe we should allocate, copy, deallocate -- to make the code simpler. An error here would be rather hard to test for. However, this makes the memory limit computation subtle -- at the peak, both allocations are counted; is that what we want?

Comment (oli-obk) [inline src/memory.rs]: Yea. That's fine with me

File: src/memory.rs (hunk 4 above)
Comment (RalfJung) [inline src/memory.rs]: But where should `free` get that information from? It's not passed in by the caller, so all it could do is ask the memory subsystem, which makes the checks entirely redundant.

File: src/memory.rs (hunk 3 above)
Comment (RalfJung) [inline src/memory.rs]: Ah, that explains it!  I will update the comment.

File: src/memory.rs (hunk 4 above)
Comment (oli-obk) [inline src/memory.rs]: You do not need to ask the memory, it is statically known that malloc and free have an alignment of `pointer_size`. But I forgot about the allocation size, so this is fine

**Comment by RalfJung** [comment]
*confused* I thought you wanted me to do some changes? (Like, change realloc to do alloc-copy-dealloc.)

**Comment by oli-obk** [comment]
That can  done in a future PR. It's only a simplification. The other changes are good, so I wanted to move them through. Also I forgot :P

File: tests/compile-fail/deallocate-bad-size.rs [hunk 5]
```diff
@@ -0,0 +1,13 @@
...
+
+extern crate alloc;
+
+// error-pattern: tried to deallocate or reallocate using incorrect alignment or size
+
+use alloc::heap::*;
+fn main() {
+    unsafe {
+        let x = allocate(1, 1);
+        deallocate(x, 1, 2);
```
Comment (bjorn3) [inline tests/compile-fail/deallocate-bad-size.rs]: This is the same as the test above.
