### PR TITLE
refactor drop glue and fix Box<Box<Struct>> as Box<Trait>

### LINKED ISSUE #129: drop in `Box<Box<T>>` as `Box<Trait>` broken
https://github.com/rust-lang/rust/pull/39230 changed some things around with boxed, especially that there is a "`Drop` impl" now: https://github.com/rust-lang/rust/blame/master/src/liballoc/boxed.rs#L297 (it's empty, doesn't drop its contents)

We should just wait for rustc to fix it.

repro:

```rust
#![feature(box_syntax)]

struct DroppableStruct;

static mut DROPPED: bool = false;

impl Drop for DroppableStruct {
    fn drop(&mut self) {
        unsafe { DROPPED = true; }
    }
}

trait MyTrait { fn dummy(&self) { } }
impl MyTrait for Box<DroppableStruct> {}

struct Whatever { w: Box<MyTrait+'static> }
impl  Whatever {
    fn new(w: Box<MyTrait+'static>) -> Whatever {
        Whatever { w: w }
    }
}

fn main() {
    {
        let f: Box<_> = box DroppableStruct;
        let _a = Whatever::new(box f as Box<MyTrait>);
    }
    assert!(unsafe { DROPPED });
}
```

### PR DESCRIPTION
**Pull request by oli-obk**
fixes #129

the commits are best viewed each on its own

### CODE REVIEW

File: src/memory.rs [hunk 1]
```diff
@@ -120,9 +120,9 @@ pub enum Function<'tcx> {
     Concrete(FunctionDefinition<'tcx>),
     /// Glue required to call a regular function through a Fn(Mut|Once) trait object
     FnDefAsTraitObject(FunctionDefinition<'tcx>),
-    /// Glue required to call the actual drop impl's `drop` method.
-    /// Drop glue takes the `self` by value, while `Drop::drop` take `&mut self`
-    DropGlue(FunctionDefinition<'tcx>),
+    /// A drop glue function only needs to know the real type, and then miri can extract the
+    /// actual type at runtime.
```
Comment (solson) [inline src/memory.rs]: Can you clarify "real type" vs "actual type"?
