### PR TITLE
compute the offset of dst fields by checking the vtable

### LINKED ISSUE #123: wrong field access on unsized types
The `f.b` access goes to offset 2, while it should be offset 8 due to the alignment of T. The issue is that in `eval_lvalue_projection` the `base_ty` is `Foo<Bar>`, so the layout computed by rustc says "hey we can put `T` directly after `a` without padding". I'm completely baffled as to how rustc does these things. Is there some info in the vtable we can use?

```rust
struct Foo<T: ?Sized> {
    a: u16,
    b: T
}

trait Bar {
    fn get(&self) -> usize;
}

impl Bar for usize {
    fn get(&self) -> usize { *self }
}

fn main() {
    let f : Foo<usize> = Foo { a: 0, b: 11 };
    let f : &Foo<Bar> = &f;
    assert_eq!(f.b.get(), 11);
}
```

```
TRACE:miri::eval_context: load mir DefId { krate: CrateNum(0), node: DefIndex(13) => dst_field_align/4089d7c8b778d88cec885baf7b69e6df-exe::main[0] }
TRACE:miri::step:  StorageLive(_1)
TRACE:miri::step:  _1 = Foo<usize> { a: const 0u16, b: const 11usize }
TRACE:miri::eval_context:  _1: Undef
TRACE:miri::memory:  allocate: 16, 8 at AllocId(2)
TRACE:miri::eval_context:  _1:
TRACE:miri::memory:  Alloc 2:    00 00 __ __ __ __ __ __ 0b 00 00 00 00 00 00 00 (16 bytes)
TRACE:miri::step:  StorageLive(_2)
TRACE:miri::step:  StorageLive(_3)
TRACE:miri::step:  StorageLive(_4)
TRACE:miri::step:  _4 = &_1
TRACE:miri::eval_context:  _4: Undef
TRACE:miri::eval_context:  _1:
TRACE:miri::memory:  Alloc 2:    00 00 __ __ __ __ __ __ 0b 00 00 00 00 00 00 00 (16 bytes)
TRACE:miri::eval_context:  _4: Ptr(Pointer { alloc_id: AllocId(2), offset: 0 })
TRACE:miri::memory:  Alloc 2:    00 00 __ __ __ __ __ __ 0b 00 00 00 00 00 00 00 (16 bytes)
TRACE:miri::step:  _3 = &(*_4)
TRACE:miri::eval_context:  _3: Undef
TRACE:miri::eval_context:  _4: Ptr(Pointer { alloc_id: AllocId(2), offset: 0 })
TRACE:miri::memory:  Alloc 2:    00 00 __ __ __ __ __ __ 0b 00 00 00 00 00 00 00 (16 bytes)
TRACE:miri::eval_context:  _4: Ptr(Pointer { alloc_id: AllocId(2), offset: 0 })
TRACE:miri::memory:  Alloc 2:    00 00 __ __ __ __ __ __ 0b 00 00 00 00 00 00 00 (16 bytes)
TRACE:miri::lvalue:  deref to Foo<usize> on ByVal(Ptr(Pointer { alloc_id: AllocId(2), offset: 0 }))
TRACE:miri::eval_context:  _3: Ptr(Pointer { alloc_id: AllocId(2), offset: 0 })
TRACE:miri::memory:  Alloc 2:    00 00 __ __ __ __ __ __ 0b 00 00 00 00 00 00 00 (16 bytes)
TRACE:miri::step:  _2 = _3 as &Foo<Bar> (Unsize)
TRACE:miri::eval_context:  _2: Undef
TRACE:miri::eval_context:  _3: Ptr(Pointer { alloc_id: AllocId(2), offset: 0 })
TRACE:miri::memory:  Alloc 2:    00 00 __ __ __ __ __ __ 0b 00 00 00 00 00 00 00 (16 bytes)
DEBUG:miri::vtable: get_vtable(trait_ref=Binder(<usize as Bar>))
DEBUG:miri::vtable: get_vtable_methods(impl_id=DefId { krate: CrateNum(0), node: DefIndex(10) => dst_field_align/4089d7c8b778d88cec885baf7b69e6df-exe::{{impl}}[0] }, substs=Slice([])
DEBUG:miri::vtable: get_vtable_methods: trait_method_type=AssociatedItem { def_id: DefId { krate: CrateNum(0), node: DefIndex(8) => dst_field_align/4089d7c8b778d88cec885baf7b69e6df-exe::Bar[0]::get[0] }, name: get(88), kind: Method, vis: Restricted(DefId { krate: CrateNum(0), node: DefIndex(0) => dst_field_align/4089d7c8b778d88cec885baf7b69e6df-exe }), defaultness: Default { has_value: false }, container: TraitContainer(DefId { krate: CrateNum(0), node: DefIndex(7) => dst_field_align/4089d7c8b778d88cec885baf7b69e6df-exe::Bar[0] }), method_has_self_argument: true }
DEBUG:miri::vtable: get_vtable_methods: trait_method_type=AssociatedItem { def_id: DefId { krate: CrateNum(0), node: DefIndex(8) => dst_field_align/4089d7c8b778d88cec885baf7b69e6df-exe::Bar[0]::get[0] }, name: get(88), kind: Method, vis: Restricted(DefId { krate: CrateNum(0), node: DefIndex(0) => dst_field_align/4089d7c8b778d88cec885baf7b69e6df-exe }), defaultness: Default { has_value: false }, container: TraitContainer(DefId { krate: CrateNum(0), node: DefIndex(7) => dst_field_align/4089d7c8b778d88cec885baf7b69e6df-exe::Bar[0] }), method_has_self_argument: true }
DEBUG:miri::vtable: get_vtable_methods: mth=ImplMethod { method: AssociatedItem { def_id: DefId { krate: CrateNum(0), node: DefIndex(11) => dst_field_align/4089d7c8b778d88cec885baf7b69e6df-exe::{{impl}}[0]::get[0] }, name: get(88), kind: Method, vis: Public, defaultness: Final, container: ImplContainer(DefId { krate: CrateNum(0), node: DefIndex(10) => dst_field_align/4089d7c8b778d88cec885baf7b69e6df-exe::{{impl}}[0] }), method_has_self_argument: true }, substs: Slice([]), is_provided: false }
DEBUG:miri::memory: creating fn ptr: 3
TRACE:miri::memory:  allocate: 32, 8 at AllocId(4)
TRACE:miri::memory:  mark_static_initalized
TRACE:miri::memory:  Alloc 4:    00 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 (32 bytes)
TRACE:miri::memory:                                                                                      └─────────(3)─────────┘ 
TRACE:miri::memory:  Alloc 3:     function pointer: <usize as Bar>::get: fn(&usize) -> usize
TRACE:miri::memory:  sub-reloc: AllocId(3)
TRACE:miri::memory:  mark_static_initalized
TRACE:miri::memory:  Alloc 3:     function pointer: <usize as Bar>::get: fn(&usize) -> usize
TRACE:miri::eval_context:  _2: (Ptr(Pointer { alloc_id: AllocId(2), offset: 0 }), Ptr(Pointer { alloc_id: AllocId(4), offset: 0 }))
TRACE:miri::memory:  Alloc 2:    00 00 __ __ __ __ __ __ 0b 00 00 00 00 00 00 00 (16 bytes)
TRACE:miri::memory:  Alloc 4:    00 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 (32 bytes) (immutable)
TRACE:miri::memory:                                                                                      └─────────(3)─────────┘ 
TRACE:miri::memory:  Alloc 3:     function pointer: <usize as Bar>::get: fn(&usize) -> usize
TRACE:miri::step:  StorageDead(_3)
TRACE:miri::step:  StorageDead(_4)
TRACE:miri::step:  StorageLive(_6)
TRACE:miri::step:  StorageLive(_7)
TRACE:miri::step:  StorageLive(_8)
TRACE:miri::step:  StorageLive(_9)
```

This is where the fun begins. We don't have the real type info available anymore, since we did an unsize cast above.

```
TRACE:miri::step:  _9 = &((*_2).1: Bar)
TRACE:miri::eval_context:  _9: Undef
TRACE:miri::eval_context:  _2: (Ptr(Pointer { alloc_id: AllocId(2), offset: 0 }), Ptr(Pointer { alloc_id: AllocId(4), offset: 0 }))
TRACE:miri::memory:  Alloc 2:    00 00 __ __ __ __ __ __ 0b 00 00 00 00 00 00 00 (16 bytes)
TRACE:miri::memory:  Alloc 4:    00 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 (32 bytes) (immutable)
TRACE:miri::memory:                                                                                      └─────────(3)─────────┘ 
TRACE:miri::memory:  Alloc 3:     function pointer: <usize as Bar>::get: fn(&usize) -> usize
TRACE:miri::eval_context:  _2: (Ptr(Pointer { alloc_id: AllocId(2), offset: 0 }), Ptr(Pointer { alloc_id: AllocId(4), offset: 0 }))
TRACE:miri::memory:  Alloc 2:    00 00 __ __ __ __ __ __ 0b 00 00 00 00 00 00 00 (16 bytes)
TRACE:miri::memory:  Alloc 4:    00 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 (32 bytes) (immutable)
TRACE:miri::memory:                                                                                      └─────────(3)─────────┘ 
TRACE:miri::memory:  Alloc 3:     function pointer: <usize as Bar>::get: fn(&usize) -> usize
TRACE:miri::lvalue:  deref to Foo<Bar> on ByValPair(Ptr(Pointer { alloc_id: AllocId(2), offset: 0 }), Ptr(Pointer { alloc_id: AllocId(4), offset: 0 }))
TRACE:miri::lvalue:  field base layout for ty Foo<Bar>: Univariant {
    variant: Struct {
        align: Align {
            raw: 49
        },
        packed: false,
        sized: false,
        offsets: [
            Size {
                raw: 0
            },
            Size {
                raw: 2
            }
        ],
        memory_index: [
            0,
            1
        ],
        min_size: Size {
            raw: 2
        }
    },
    non_zero: false
}
TRACE:miri::lvalue:  field: 1 at offset 2
```

see how `_9` points to offset 2 in alloc 2.

```
TRACE:miri::eval_context:  _9: (Ptr(Pointer { alloc_id: AllocId(2), offset: 2 }), Ptr(Pointer { alloc_id: AllocId(4), offset: 0 }))
TRACE:miri::memory:  Alloc 2:    00 00 __ __ __ __ __ __ 0b 00 00 00 00 00 00 00 (16 bytes)
TRACE:miri::memory:  Alloc 4:    00 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 (32 bytes) (immutable)
TRACE:miri::memory:                                                                                      └─────────(3)─────────┘ 
TRACE:miri::memory:  Alloc 3:     function pointer: <usize as Bar>::get: fn(&usize) -> usize
TRACE:miri::step:  _8 = <Bar as Bar>::get(_9) -> bb1
TRACE:miri::eval_context:  _8: Undef
TRACE:miri::eval_context:  _9: (Ptr(Pointer { alloc_id: AllocId(2), offset: 2 }), Ptr(Pointer { alloc_id: AllocId(4), offset: 0 }))
TRACE:miri::memory:  Alloc 2:    00 00 __ __ __ __ __ __ 0b 00 00 00 00 00 00 00 (16 bytes)
TRACE:miri::memory:  Alloc 4:    00 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 (32 bytes) (immutable)
TRACE:miri::memory:                                                                                      └─────────(3)─────────┘ 
TRACE:miri::memory:  Alloc 3:     function pointer: <usize as Bar>::get: fn(&usize) -> usize
TRACE:miri::terminator:  args: [
    (
        ByValPair(
            Ptr(
                Pointer {
                    alloc_id: AllocId(
                        2
                    ),
                    offset: 2
                }
            ),
            Ptr(
                Pointer {
                    alloc_id: AllocId(
                        4
                    ),
                    offset: 0
                }
            )
        ),
        &Bar
    )
]
DEBUG:miri::memory: reading fn ptr: 3
TRACE:miri::terminator:  sig: ([&usize]; variadic: false)->usize
TRACE:miri::eval_context:  load mir DefId { krate: CrateNum(0), node: DefIndex(11) => dst_field_align/4089d7c8b778d88cec885baf7b69e6df-exe::{{impl}}[0]::get[0] }
TRACE:miri::eval_context:   _1: Undef
TRACE:miri::step:   // bb0
TRACE:miri::step:   StorageLive(_2)
TRACE:miri::step:   _2 = _1
TRACE:miri::eval_context:   _2: Undef
TRACE:miri::eval_context:   _1: Ptr(Pointer { alloc_id: AllocId(2), offset: 2 })
TRACE:miri::memory:   Alloc 2:    00 00 __ __ __ __ __ __ 0b 00 00 00 00 00 00 00 (16 bytes)
TRACE:miri::eval_context:   _2: Ptr(Pointer { alloc_id: AllocId(2), offset: 2 })
TRACE:miri::memory:   Alloc 2:    00 00 __ __ __ __ __ __ 0b 00 00 00 00 00 00 00 (16 bytes)
TRACE:miri::step:   StorageLive(_3)
TRACE:miri::step:   _3 = (*_2)
TRACE:miri::eval_context:   _3: Undef
TRACE:miri::eval_context:   _2: Ptr(Pointer { alloc_id: AllocId(2), offset: 2 })
TRACE:miri::memory:   Alloc 2:    00 00 __ __ __ __ __ __ 0b 00 00 00 00 00 00 00 (16 bytes)
TRACE:miri::eval_context:   _2: Ptr(Pointer { alloc_id: AllocId(2), offset: 2 })
TRACE:miri::memory:   Alloc 2:    00 00 __ __ __ __ __ __ 0b 00 00 00 00 00 00 00 (16 bytes)
TRACE:miri::lvalue:   deref to usize on ByVal(Ptr(Pointer { alloc_id: AllocId(2), offset: 2 }))
TRACE:miri::memory:   allocate: 8, 8 at AllocId(5)
TRACE:miri::memory:   alignment check 2 failed for alloc AllocId(2)
error: tried to access memory with alignment 2, but alignment 8 is required
  --> tests/run-pass/dst-field-align.rs:21:30
   |
21 |     fn get(&self) -> usize { *self }
   |                              ^^^^^
   |
note: inside call to <usize as Bar>::get
  --> tests/run-pass/dst-field-align.rs:27:16
   |
27 |     assert_eq!(f.b.get(), 11);
   |                ^^^^^^^^^
note: inside call to main
```

### PR DESCRIPTION
**Pull request by oli-obk**
fixes #123

### CODE REVIEW

File: src/lvalue.rs [hunk 1]
```diff
@@ -214,7 +214,16 @@ impl<'a, 'tcx> EvalContext<'a, 'tcx> {
                     _ => bug!("field access on non-product type: {:?}", base_layout),
                 };
 
-                let ptr = base_ptr.offset(offset.bytes());
+                let offset = match base_extra {
+                    LvalueExtra::Vtable(tab) => {
+                        let (_, align) = self.size_and_align_of_dst(base_ty, Value::ByValPair(PrimVal::Ptr(base_ptr), PrimVal::Ptr(tab)))?;
+                        // magical formula taken from rustc
+                        (offset.bytes() + (align - 1)) & (-(align as i64) as u64)
```
Comment (eddyb) [inline src/lvalue.rs]: This is `.align_to` on `Size`, isn't it? I mean, there shouldn't be more than one such function anywhere, in Rust (you could still have this generated as several instructions like we do in trans, but that's not relevant here
