### PR TITLE
Produce backtraces for miri internals

### LINKED ISSUE #251: Provide inner (miri) backtraces
When miri generates an error, it should be possible to get a backtrace of where the error originated.

I kind of thought we'd need error_chain for that, but @oli-obk suggested we could just use the backtrace crate.

### PR DESCRIPTION
**Pull request by oli-obk**
fixes #251

### CODE REVIEW

File: src/librustc_mir/interpret/error.rs [hunk 1]
```diff
@@ -192,7 +228,7 @@ impl<'tcx> Error for EvalError<'tcx> {
             TypeNotPrimitive(_) =>
                 "expected primitive type, got nonprimitive",
             ReallocatedWrongMemoryKind(_, _) =>
-                "tried to reallocate memory from one kind to another",
+                "tried to EvalErrorKindreallocate memory from one kind to another",
```
Comment (RalfJung) [inline src/librustc_mir/interpret/error.rs]: This looks like an accidental edit.

File: src/librustc_mir/interpret/mod.rs [hunk 2]
```diff
@@ -1,5 +1,10 @@
 //! An interpreter for MIR used in CTFE and by miri
 
+#[macro_export]
+macro_rules! err {
+    ($($tt:tt)*) => { Err($crate::interpret::EvalErrorKind::$($tt)*.into()) };
+}
```
Comment (RalfJung) [inline src/librustc_mir/interpret/mod.rs]: What about moving this to error.rs? I think it'd make more sense to have it there.

File: src/librustc_mir/interpret/error.rs [hunk 3]
```diff
@@ -11,7 +13,41 @@ use rustc_const_math::ConstMathErr;
...
+        trace(|frame| {
+            resolve(frame.ip(), |symbol| {
+                backtrace.push(Frame {
+                    function: symbol.name().map(|s| s.to_string()).unwrap_or(String::new()),
+                    file: symbol.filename().unwrap_or(Path::new("")).to_owned(),
+                    line: symbol.lineno().unwrap_or(0),
+                });
+            });
+            true
+        });
```
Comment (RalfJung) [inline src/librustc_mir/interpret/error.rs]: The backtrace crate also has this type which just captures the entire backtrace at once:
<http://alexcrichton.com/backtrace-rs/backtrace/struct.Backtrace.html>
Why did you end up doing the more manual capturing here?

File: src/librustc_mir/interpret/error.rs (hunk 1 above)
Comment (oli-obk) [inline src/librustc_mir/interpret/error.rs]: regex replacements :/ good catch

File: src/librustc_mir/interpret/mod.rs (hunk 2 above)
Comment (oli-obk) [inline src/librustc_mir/interpret/mod.rs]: macro ordering is important. If we move it to `error.rs`, we need to ensure that the `mod error` is the first one in the list, otherwise the modules above don't get the macro.

File: tests/compiletest.rs [hunk 4]
```diff
@@ -13,11 +13,16 @@ macro_rules! eprintln {
     }
 }
 
+#[cfg(debug_assertions)]
+const MIRI_PATH: &str = "target/debug/miri";
+#[cfg(not(debug_assertions))]
+const MIRI_PATH: &str = "target/release/miri";
```
Comment (oli-obk) [inline tests/compiletest.rs]: I don't know how else to make this distinction

File: src/librustc_mir/interpret/mod.rs (hunk 2 above)
Comment (RalfJung) [inline src/librustc_mir/interpret/mod.rs]: Oh, I see. I did not know that. I got used to ordering not mattering in Rust. ;)

Comment (eddyb) [inline src/librustc_mir/interpret/mod.rs]: macros 2.0 will solve it.

File: tests/compiletest.rs (hunk 4 above)
Comment (RalfJung) [inline tests/compiletest.rs]: I pushed a commit that hopefully should fix this. (#rust IRC channel was very helpful :) )

File: tests/compiletest.rs [hunk 5]
```diff
@@ -13,16 +13,15 @@ macro_rules! eprintln {
     }
 }
 
-#[cfg(debug_assertions)]
-const MIRI_PATH: &str = "target/debug/miri";
-#[cfg(not(debug_assertions))]
-const MIRI_PATH: &str = "target/release/miri";
+fn miri_path() -> String {
+    format!("target/{}/miri", env!("PROFILE"))
```
Comment (eddyb) [inline tests/compiletest.rs]: You can do this with `const` and `concat!("target/", env!("PROFILE"), "/miri")`.

Comment (RalfJung) [inline tests/compiletest.rs]: Ah, nice. Will do.

File: tests/compiletest.rs [hunk 6]
```diff
@@ -13,8 +13,8 @@ macro_rules! eprintln {
     }
 }
 
-fn miri_path() -> String {
-    format!("target/{}/miri", env!("PROFILE"))
+const fn miri_path() -> &'static str {
+    concat!("target/", env!("PROFILE"), "/miri")
```
Comment (eddyb) [inline tests/compiletest.rs]: You don't need a `const fn`. You can use a plain `const`.

Comment (RalfJung) [inline tests/compiletest.rs]: Ah, right. Done.

**Comment by RalfJung** [comment]
This has incurred a HUGE performance regression in validation mode. There, we frequently generate an `Err` and catch it again, and it seems capturing a backtrace is extremely expensive.

**Comment by RalfJung** [comment]
Probably resolving symbols takes a while; this could involve loading debug info and whatnot. I suppose we will, after all, have to switch to the more low-level API you used first.

**Comment by oli-obk** [comment]
Let's get rid of the captures then. They aren't pretty anyway.

**Comment by oli-obk** [comment]
I resolve symbols on the low level API, too. Alternatively we can just capture the stack frame pointers, but I think fixing the captures is cleaner

**Comment by RalfJung** [comment]
Wait but capturing them was the entire point wasn't it? Also see <https://github.com/alexcrichton/backtrace-rs/issues/30>. We can delay resolving until printing.

**Comment by RalfJung** [comment]
To further improve performance, we could check RUST_BACKTRACE and only actually capture and print anything if it is non-empty.

**Comment by eddyb** [comment]
@oli-obk `error-chain` checks `RUST_BACKTRACE`, you should've just used that, lol.

**Comment by RalfJung** [comment]
I am now going back to @oli-obk's original approach, plus checking RUST_BACKTRACE, plus delaying symbol resolution until printing.

**Comment by oli-obk** [comment]
@eddyb error-chain is hard to integrate with our system due to the extensibility of the error via the machine. I have not found a way to make error-chain create a generic error type

**Comment by RalfJung** [comment]
See <https://github.com/solson/miri/pull/283>.
