### PR TITLE
Only check pointers when dereferencing

### LINKED ISSUE #228: `let x = *Box::new(());` tries to write to integer pointer
Our handling of lvalues is wrong. We turn an lvalue pointing to an integer address to a `ByRef` iff one tries to read from the lvalue. That's obviously bad for zsts.

I don't think we should convert an `Lvalue` into a `ByRef` ever. I suggest we create an `Rvalue` type, which is just a thin wrapper around `Lvalue` that forbids writing to it.

The alternative would be to add more special zst code, but I suspect this abuse of `ByRef` as rvalues is going to bite us elsewhere, too. It just feels like an accident waiting to happen.

### PR DESCRIPTION
**Pull request by oli-obk**
Before we also checked whether pointers had alloc_ids when we created rvalue references

fixes #228

### CODE REVIEW

File: src/value.rs [hunk 1]
```diff
@@ -33,7 +33,7 @@ pub(super) fn f64_to_bytes(f: f64) -> u128 {
 /// operations and fat pointers. This idea was taken from rustc's trans.
 #[derive(Clone, Copy, Debug)]
 pub enum Value {
-    ByRef(Pointer),
+    ByRef(PrimVal),
```
Comment (RalfJung) [inline src/value.rs]: This is the key change, right? Everything else essentially just makes the types work out again?

Things would be a little nicer if this was not necessary, but I suppose with ZSTs we don't really have an alternative. So, LGTM.

Comment (oli-obk) [inline src/value.rs]: > This is the key change, right? Everything else essentially just makes the types work out again?

Pretty much, yea.

> Things would be a little nicer if this was not necessary, but I suppose with ZSTs we don't really have an alternative.

This should also make implementing the intptrcast easier ;)
